[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd commerce && npm install"]

[phases.build]
cmds = ["cd commerce && npm run build"]

[start]
cmd = "cd commerce && npx medusa db:migrate && npm run start"