export { default as HeroSection } from './hero-section'
export { default as ProductPatchesSection } from './product-patches-section'
export { default as ComparisonSection } from './comparison-section'
export { default as HowItWorksSection } from './how-it-works-section'
export { default as TestimonialsSection } from './testimonials-section'
export { default as FAQSection } from './faq-section'
export { default as FeaturedProducts } from './featured-products'
